name: safestreet
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # ✅ Flexible Dart version

dependencies:
  flutter:
    sdk: flutter

  # ✅ Core UI Dependencies
  cupertino_icons: ^1.0.8

  # ✅ Firebase Dependencies (Latest versions)
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_storage: ^11.6.5

  # ✅ Location & Maps
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.0

  # ✅ State Management (Optional)
  provider: ^6.1.5

  # ✅ Augmented Reality (Fixing `ar_flutter_plugin` issue)
  ar_flutter_plugin: 
    git:
      url: https://github.com/viromedia/arcore-flutter-plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
